<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aeox.Core\Aeox.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Aeox</AssemblyName>
    <RootNamespace>Aeox.App</RootNamespace>
    <Product>Aeox</Product>
    <Version>0.1.0</Version>
    <ApplicationIcon>Assets\aeox.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\aeox.ico" />
  </ItemGroup>

</Project>
